export const effectsList = {

  beauty_touch_up: {
    label: "Редактор лица",
    categories: {
      facemorphing: {
        label: "Форма лица",
        effects: [
          {
            name: "Morphings_1.7.0.zip",
            control: "slider",
            params: ["FaceMorph.face"],
            arg: "narrowing",
            direction: 1,
            icon: "face_narrowing.svg",
          },
          {
            name: "Morphings_1.7.0.zip",
            control: "slider",
            params: ["FaceMorph.face"],
            arg: "v_shape",
            direction: 1,
            icon: "face_v_shape.svg",
          },
          {
            name: "Morphings_1.7.0.zip",
            control: "slider",
            params: ["FaceMorph.face"],
            arg: "cheekbones_narrowing",
            direction: 1,
            icon: "face_cheekbones_narrowing.svg",
          },
          {
            name: "Morphings_1.7.0.zip",
            control: "slider",
            params: ["FaceMorph.face"],
            arg: "cheeks_narrowing",
            direction: 1,
            icon: "face_cheeks_narrowing.svg",
          },
          {
            name: "Morphings_1.7.0.zip",
            control: "slider",
            params: ["FaceMorph.face"],
            arg: "jaw_narrowing",
            direction: 1,
            icon: "face_jaw_narrowing.svg",
          },
          {
            name: "Morphings_1.7.0.zip",
            control: "slider",
            params: ["FaceMorph.face"],
            arg: "chin_shortening",
            direction: 1,
            icon: "face_chin_shortening.svg",
          },
          {
            name: "Morphings_1.7.0.zip",
            control: "slider",
            params: ["FaceMorph.face"],
            arg: "chin_narrowing",
            direction: 1,
            icon: "face_chin_narrowing.svg",
          },
          {
            name: "Morphings_1.7.0.zip",
            control: "slider",
            params: ["FaceMorph.face"],
            arg: "sunken_cheeks",
            minValue: "0",
            direction: 1,
            icon: "face_sunken_cheeks.svg",
          },
          {
            name: "Morphings_1.7.0.zip",
            control: "slider",
            params: ["FaceMorph.face"],
            arg: "cheeks_jaw_narrowing",
            direction: 1,
            icon: "face_cheeks_jaw_narrowing.svg",
          },
        ],
      },
      nose: {
        label: "Нос",
        effects: [
          {
            name: "Morphings_1.7.0.zip",
            control: "slider",
            params: ["FaceMorph.nose"],
            arg: "width",
            direction: 1,
            icon: "nose_width.svg",
          },
          {
            name: "Morphings_1.7.0.zip",
            control: "slider",
            params: ["FaceMorph.nose"],
            arg: "length",
            direction: 1,
            icon: "nose_length.svg",
          },
          {
            name: "Morphings_1.7.0.zip",
            control: "slider",
            params: ["FaceMorph.nose"],
            arg: "tip_width",
            direction: -1,
            icon: "nose_tip_width.svg",
          },
        ],
      },
      eyes: {
        label: "Глаза",
        effects: [
          {
            name: "Morphings_1.7.0.zip",
            control: "slider",
            params: ["FaceMorph.eyes"],
            arg: "rounding",
            minValue: "0",
            direction: 1,
            icon: "eyes_rounding.svg",
          },
          {
            name: "Morphings_1.7.0.zip",
            control: "slider",
            params: ["FaceMorph.eyes"],
            arg: "enlargement",
            direction: 1,
            icon: "eyes_enlargement.svg",
          },
          {
            name: "Morphings_1.7.0.zip",
            control: "slider",
            params: ["FaceMorph.eyes"],
            arg: "height",
            direction: 1,
            icon: "eyes_height.svg",
          },
          {
            name: "Morphings_1.7.0.zip",
            control: "slider",
            params: ["FaceMorph.eyes"],
            arg: "spacing",
            direction: 1,
            icon: "eyes_spacing.svg",
          },
          {
            name: "Morphings_1.7.0.zip",
            control: "slider",
            params: ["FaceMorph.eyes"],
            arg: "squint",
            direction: -1,
            icon: "eyes_squint.svg",
          },
          {
            name: "Morphings_1.7.0.zip",
            control: "slider",
            params: ["FaceMorph.eyes"],
            arg: "lower_eyelid_pos",
            direction: 1,
            icon: "eyes_lower_eyelid_pos.svg",
          },
          {
            name: "Morphings_1.7.0.zip",
            control: "slider",
            params: ["FaceMorph.eyes"],
            arg: "lower_eyelid_size",
            direction: -1,
            icon: "eyes_lower_eyelid_size.svg",
          },
        ],
      },
      eyebrows: {
        label: "Брови",
        effects: [
          {
            name: "Morphings_1.7.0.zip",
            control: "slider",
            params: ["FaceMorph.eyebrows"],
            arg: "spacing",
            direction: -1,
            icon: "eyebrows_spacing.svg",
          },
          {
            name: "Morphings_1.7.0.zip",
            control: "slider",
            params: ["FaceMorph.eyebrows"],
            arg: "height",
            direction: -1,
            icon: "eyebrows_height.svg",
          },
          {
            name: "Morphings_1.7.0.zip",
            control: "slider",
            params: ["FaceMorph.eyebrows"],
            arg: "bend",
            direction: 1,
            icon: "eyebrows_bend.svg",
          },
        ],
      },
      lips: {
        label: "Губы",
        effects: [
          {
            name: "Morphings_1.7.0.zip",
            control: "slider",
            params: ["FaceMorph.lips"],
            direction: 1,
            arg: "size",
            icon: "lips_size.svg",
          },
          {
            name: "Morphings_1.7.0.zip",
            control: "slider",
            params: ["FaceMorph.lips"],
            direction: 1,
            arg: "height",
            icon: "lips_height.svg",
          },
          {
            name: "Morphings_1.7.0.zip",
            control: "slider",
            params: ["FaceMorph.lips"],
            direction: 1,
            arg: "thickness",
            icon: "lips_thickness.svg",
          },
          {
            name: "Morphings_1.7.0.zip",
            control: "slider",
            params: ["FaceMorph.lips"],
            direction: -1,
            arg: "mouth_size",
            icon: "lips_mouth_size.svg",
          },
          {
            name: "Morphings_1.7.0.zip",
            control: "slider",
            params: ["FaceMorph.lips"],
            direction: 1,
            minValue: "0",
            arg: "smile",
            icon: "lips_smile.svg",
          },
          {
            name: "Morphings_1.7.0.zip",
            control: "slider",
            params: ["FaceMorph.lips"],
            direction: -1,
            arg: "shape",
            icon: "lips_shape.svg",
          },
        ],
      },
      skin: {
        label: "Кожа",
        effects: [
          {
            name: "SkinSoftening.zip",
            control: "slider",
            params: ["Skin.softening"],
            minValue: 0,
            direction: 1,
          },
        ],
      },
      eye_whitening: {
        label: "Белые глаза",
        effects: [
          {
            name: "EyesWitening_Toggle.zip",
            control: "toggle",
            params: ["onDataUpdate"],
          },
        ],
      },
    },
  },

  virtual_try_on: {
    label: "Виртуальный макияж",
    categories: {
      glasses_try_on: {
        label: "Цвет глаз",
        effects: [
          { name: "Eye_lenses_Blue.zip", icon: "Eye_lenses_Blue.png" },
          { name: "Eye_lenses_Green.zip", icon: "Eye_lenses_Green.png" },
          { name: "glasses_RayBan4165_Dark.zip", icon: "Glasses_Dark.png" },
        ],
      },
      hair: {
        label: "Цвет волос",
        effects: [
          { name: "VTO_Hair_blue.zip", icon: "VTO_Hair_blue.png" },
          { name: "VTO_Hair_green.zip", icon: "VTO_Hair_green.png" },
          { name: "VTO_Hair_strand.zip", icon: "VTO_Hair_strand.png" },
        ],
      },
      makeup: {
        label: "Макияж",
        effects: [{ name: "Low_look_clubs.zip" }],
      },
      makeup1: {
        label: "Деловой",
        effects: [{ name: "delov.zip" }],
      },
      makeup2: {
        label: "Креативный/яркий",
        effects: [{ name: "Creativ.zip" }],
      },
      makeup3: {
        label: "Романтический",
        effects: [{ name: "roman.zip" }],
      },
      makeup4: {
        label: "Свадебный",
        effects: [{ name: "svadeb.zip" }],
      },
      makeup5: {
        label: "Летний цветотип",
        effects: [{ name: "leto.zip" }],
      },
      makeup6: {
        label: "Весенний цветотип",
        effects: [{ name: "vesna.zip" }],
      },
      makeup7: {
        label: "Осенний цветотип",
        effects: [{ name: "osen.zip" }],
      },
      makeup8: {
        label: "Зимний цветотип",
        effects: [{ name: "zima.zip" }],
      },
    },
  }
};
